local g = vim.g
local o = vim.o

g.mapleader = " " -- Set the leader key to Space
g.maplocalleader = "\\" -- Set the local leader key to Backslash
o.backup = false
o.breakindent = true -- Enable break indent
o.clipboard = "unnamedplus" -- Use system clipboard
o.cmdheight = 0 -- Set command line height to 0
o.confirm = true -- Ask for confirmation instead of erroring
o.conceallevel = 0
o.cursorline = true -- Highlight the current line
o.expandtab = true -- Use spaces instead of tabs
o.foldenable = true -- Enable folding
o.foldlevelstart = 99 -- Start with all folds open
o.foldtext = ""
o.foldcolumn = "0"
o.foldmethod = "expr"
o.fillchars = "fold: ,diff:/" -- Set fill characters for folds
o.hlsearch = true -- Highlight search results
o.ignorecase = true -- Ignore case in search patterns
o.inccommand = "split" -- Show effects of a command incrementally
o.jumpoptions = "stack"
o.laststatus = 3 -- Always display the status line
o.list = true -- Show invisible characters
o.listchars = "tab:» ,trail:·,nbsp:␣" -- Define symbols for invisible characters
o.mouse = "a" -- Enable mouse in all modes
o.number = true -- Show line numbers
o.ruler = false -- Hide the cursor position ruler
o.relativenumber = true -- Show relative line numbers
o.scrolloff = 8 -- Keep 8 lines visible above/below the cursor
o.sessionoptions = "buffers,curdir,tabpages,winsize,help,globals,skiprtp,folds" -- Configure session options
o.shiftwidth = 2 -- Number of spaces to use for each step of (auto)indent
o.showmode = false -- Don't display mode (e.g., -- INSERT --)
o.showcmd = false -- Don't display partial command in the last line of the screen
o.showtabline = 0
o.tabclose = "uselast"
o.sidescrolloff = 8 -- Keep 8 columns visible to the left/right of the cursor
o.signcolumn = "yes" -- Always show the sign column
o.smartcase = true -- Override ignorecase if search pattern contains uppercase letters
o.smoothscroll = true -- Enable smooth scrolling
o.title = false
-- o.scrolloff = math.floor(vim.fn.winheight(0) / 2) -- Always center the current line.
o.scrolloff = 5 -- Number of lines to keep above/below the cursor.
o.sidescrolloff = 5 -- Number of columns to keep left/right of the cursor.
o.splitbelow = true -- Horizontal splits will automatically be below
o.splitright = true -- Vertical splits will automatically be to the right
o.swapfile = false
o.tabstop = 2 -- Number of spaces that a <Tab> in the file counts for
o.termguicolors = true -- Enable 24-bit RGB color in the TUI
o.timeoutlen = 300 -- Time in milliseconds to wait for a mapped sequence to complete
o.undofile = true -- Save undo history to file
o.undolevels = 10000 -- Maximum number of changes that can be undone
o.updatetime = 250 -- Faster completion (default is 4000ms)
o.wrap = false -- Disable line wrap
